sjobs:
  - { git_repo_url: https://github.com/balatuluva/robotshop-terraform.git, job_name: roboshop-terraform }
  - { git_repo_url: https://github.com/balatuluva/robotshop-ansible.git, job_name: roboshop-ansible }